var __extends = (this && this.__extends) || (function () {
    var extendStatics = Object.setPrototypeOf ||
        ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
        function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }(); /**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


var _RankView = require("./scripts/common/RankService/RankView");

var _RankView2 = _interopRequireDefault(_RankView);

var _RankCell = require("./scripts/common/RankService/RankCell");

var _RankCell2 = _interopRequireDefault(_RankCell);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var GameConfig = function () {
    function GameConfig() {
        _classCallCheck(this, GameConfig);
    }

    _createClass(GameConfig, null, [{
        key: "init",
        value: function init() {
            //注册Script或者Runtime引用
            var reg = Laya.ClassUtils.regClass;
            reg("scripts/common/RankService/RankView.js", _RankView2.default);
            reg("scripts/common/RankService/RankCell.js", _RankCell2.default);
        }
    }]);

    return GameConfig;
}();

exports.default = GameConfig;

GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode = "fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "scenes/common/Rank/ODCRankView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();

},{"./scripts/common/RankService/RankCell":3,"./scripts/common/RankService/RankView":4}],2:[function(require,module,exports){
"use strict";

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _GameConfig = require("./GameConfig");

var _GameConfig2 = _interopRequireDefault(_GameConfig);

var _DataCenter = require("./scripts/utils/DataCenter");

var _DataCenter2 = _interopRequireDefault(_DataCenter);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Main = function () {
	function Main() {
		_classCallCheck(this, Main);

		Laya.isWXPosMsg = true;
		Laya.isWXOpenDataContext = true;
		Laya.init(750, 1334);
		Laya.stage.scaleMode = Laya.Stage.SCALE_FIXED_WIDTH;
		Laya.stage.screenMode = Laya.Stage.SCREEN_VERTICAL;
		Laya.stage.alignV = Laya.Stage.ALIGN_MIDDLE;
		Laya.stage.alignH = Laya.Stage.ALIGN_CENTER;
		//兼容微信不支持加载scene后缀场景
		Laya.URL.exportSceneToJson = true;
	}

	_createClass(Main, [{
		key: "loadScene",
		value: function loadScene(cb) {
			Laya.loader.load('res/atlas/remote/rank.atlas', Laya.Handler.create(this, function (data) {
				Laya.Scene.open('scenes/common/Rank/ODCRankView.scene', true, null, Laya.Handler.create(this, function (scene) {
					cb(scene);
				}));
			}));
		}
	}]);

	return Main;
}();

//激活启动类


var main = new Main();

if (window.wx) {
	wx.onMessage(function (data) {
		switch (data.type) {
			case 'showRankView':
				_DataCenter2.default.requestFriendList(function (list, info) {
					main.loadScene(function (scene) {
						scene.receiveData(list, info);
					});
				});
				break;
			case 'showRankGroupView':
				var shareTicket = data.shareTicket;
				_DataCenter2.default.requestGroupList(shareTicket, function (list, info) {
					main.loadScene(function (scene) {
						scene.receiveData(list, info);
					});
				});
				break;
		}
	});
}

},{"./GameConfig":1,"./scripts/utils/DataCenter":5}],3:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var RankCell = function (_Laya$Box) {
    _inherits(RankCell, _Laya$Box);

    function RankCell() {
        _classCallCheck(this, RankCell);

        return _possibleConstructorReturn(this, (RankCell.__proto__ || Object.getPrototypeOf(RankCell)).apply(this, arguments));
    }

    _createClass(RankCell, [{
        key: 'onAwake',
        value: function onAwake() {
            this.imgIcon = this.getChildByName('imgIcon');
            this.lblRank = this.getChildByName('lblRank');
            this.lblName = this.getChildByName('lblName');
            this.lblCount = this.getChildByName('lblCount');
        }
    }, {
        key: 'setItem',
        value: function setItem(item) {
            this.lblRank.text = item.rank;
            this.imgIcon.skin = item.avatarUrl;
            this.lblName.text = item.nickname;
            this.lblCount.text = item.detail;
        }
    }]);

    return RankCell;
}(Laya.Box);

exports.default = RankCell;

},{}],4:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _possibleConstructorReturn(self, call) { if (!self) { throw new ReferenceError("this hasn't been initialised - super() hasn't been called"); } return call && (typeof call === "object" || typeof call === "function") ? call : self; }

function _inherits(subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) Object.setPrototypeOf ? Object.setPrototypeOf(subClass, superClass) : subClass.__proto__ = superClass; }

var RankView = function (_Laya$View) {
    _inherits(RankView, _Laya$View);

    function RankView() {
        _classCallCheck(this, RankView);

        return _possibleConstructorReturn(this, (RankView.__proto__ || Object.getPrototypeOf(RankView)).apply(this, arguments));
    }

    _createClass(RankView, [{
        key: "onAwake",
        value: function onAwake() {
            this.configListView();
        }
    }, {
        key: "configListView",
        value: function configListView() {
            var listView = this.listView;
            listView.vScrollBarSkin = "";
            listView.renderHandler = Laya.Handler.create(this, function (cell, index) {
                var item = listView.array[index];
                cell.setItem(item);
                if (index == 0) {
                    cell.lblRank.color = "#ff7e00";
                    cell.lblRank.bold = true;
                } else if (index == 1 || index == 2) {
                    cell.lblRank.color = "#404040";
                    cell.lblRank.bold = true;
                } else {
                    cell.lblRank.color = "#7c7c7c";
                    cell.lblRank.bold = false;
                }
            }, null, false);
        }
    }, {
        key: "reloadData",
        value: function reloadData(list) {
            this.listView.repeatY = list.length > 5 ? 5 : list.length;
            this.listView.array = list;
            this.listView.refresh();
        }
    }, {
        key: "reloadMyRankViewData",
        value: function reloadMyRankViewData(data) {
            this.myRankView.setItem(data);
        }
    }, {
        key: "receiveData",
        value: function receiveData(list, info) {
            this.reloadData(list);
            this.reloadMyRankViewData(info);
        }
    }]);

    return RankView;
}(Laya.View);

exports.default = RankView;

},{}],5:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _OpenDataCtx = require('./OpenDataCtx');

var _OpenDataCtx2 = _interopRequireDefault(_OpenDataCtx);

var _Util = require('./Util');

var _Util2 = _interopRequireDefault(_Util);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var DataCenter = function DataCenter() {
    _classCallCheck(this, DataCenter);
};
/**当前用户数据 */


exports.default = DataCenter;
DataCenter.friendsInfo = null;
/**自己用户信息 */
DataCenter.myInfo = null;
/**当前用户详细信息 */
DataCenter.user = null;
/**
 * KVList:[
 *    {key:"score",value:"1000"},
 *    {key:"maxScore",value:"1000"}
 *    {key:"detail",value:"详情"},
 *    {key:"update_time",value:"123456789"},
 * ]
 */
DataCenter.makeData = function (data, cb) {
    var _this = this;

    var list = this.handleList(data);
    this.requestUserData(function (info) {
        info.rank = _this.findUserRank(info, list);
        info.detail = _this.findUserDetail(info);
        cb && cb(list, info);
    });
};
DataCenter.requestFriendList = function (cb) {
    var _this2 = this;

    _OpenDataCtx2.default.getFriendData(function (res) {
        _this2.makeData(res.data, cb);
    });
};
DataCenter.requestGroupList = function (shareTicket, cb) {
    var _this3 = this;

    _OpenDataCtx2.default.getGroupData(shareTicket, function (res) {
        _this3.makeData(res.data, cb);
    });
};
/**向服务器更新【最高分】 */
DataCenter.updateMaxScore = function (params) {
    if (!params[_OpenDataCtx2.default.SCORE_KEY]) {
        console.error("必须指定用户的分数");
        return;
    }
    var kvList = [];

    var center = DataCenter.center;
    var myInfo = center.myInfo;
    if (!myInfo) {
        return;
    }
    var score = params[_OpenDataCtx2.default.SCORE_KEY];
    var maxScore = myInfo[_OpenDataCtx2.default.SCORE_MAX_KEY];
    maxScore = Math.max(maxScore, score);

    kvList.push({
        key: _OpenDataCtx2.default.SCORE_KEY,
        value: maxScore + ""
    });
    kvList.push({
        key: _OpenDataCtx2.default.SCORE_MAX_KEY,
        value: maxScore + ""
    });

    if (params[_OpenDataCtx2.default.DES_KEY]) {
        kvList.push({
            key: _OpenDataCtx2.default.DES_KEY,
            value: params[_OpenDataCtx2.default.DES_KEY]
        });
    } else {
        kvList.push({
            key: _OpenDataCtx2.default.DES_KEY,
            value: maxScore + params['unit']
        });
    }
    _OpenDataCtx2.default.set(kvList);
};
/**获取个人信息 */
DataCenter.requestMyInfo = function (cb) {
    var _this4 = this;

    if (this.user) {
        cb && cb(this.user);
    }
    _OpenDataCtx2.default.getMyInfo(function (res) {
        var user = res.data[0];
        user.nickName = _Util2.default.formatName(user.nickName);
        user.avatarUrl = _Util2.default.makeIcon(user.avatarUrl);
        _this4.user = user;
        cb && cb(_this4.user);
    });
};
DataCenter.requestUserData = function (cb) {
    this.requestMyInfo(function (user) {
        _OpenDataCtx2.default.getUserData(function (res) {
            var info = {
                openid: "",
                nickname: user.nickName,
                avatarUrl: user.avatarUrl,
                KVDataList: res.KVDataList
            };
            cb && cb(info);
        });
    });
};

DataCenter.handleList = function (list) {
    var _this5 = this;

    var result = [];
    for (var i = 0, length = list.length; i < length; i++) {
        var info = list[i];
        var kvList = info.KVDataList;
        if (!kvList || kvList.length <= 0) {
            console.error("当前数据不存在指定的KVList:\n");
            console.log(JSON.stringify(info));
            continue;
        }
        // Util.flat(info, 'KVDataList')

        // if (!info[OpenDataCtx.SCORE_KEY]) { continue }
        // if (!info[OpenDataCtx.DES_KEY]) {
        //     info[OpenDataCtx.DES_KEY] = info[OpenDataCtx.SCORE_KEY]
        // }

        info.nickname = _Util2.default.formatName(info.nickname);
        info.avatarUrl = _Util2.default.makeIcon(info.avatarUrl);
        result.push(info);
    }
    result.forEach(function (item, idx) {
        item.rank = 'NO.' + (idx + 1);
        item.detail = _this5.findUserDetail(item);
    });
    result.sort(function (lhs, rhs) {
        return rhs.KVDataList[_OpenDataCtx2.default.SCORE_INDEX].value - lhs.KVDataList[_OpenDataCtx2.default.SCORE_INDEX].value;
    });
    return result;
};
DataCenter.findUserRank = function (user, list) {
    var userRank = -1;
    for (var i = 0; i < list.length; i++) {
        var info = list[i];
        if (info.avatarUrl == user.avatarUrl || info.nickname == user.nickname) {
            userRank = i;
        }
        info.rank = "NO." + (i + 1);
    }
    return userRank == -1 ? "未上榜" : "NO." + (userRank + 1);
};
DataCenter.findUserDetail = function (info) {
    var detail = '';
    if (info.KVDataList.length == 0){

    } else if (info.KVDataList.length > _OpenDataCtx2.default.DETAIL_INDEX) {
        detail = info.KVDataList[_OpenDataCtx2.default.DETAIL_INDEX].value || info.KVDataList[_OpenDataCtx2.default.SCORE_INDEX].value || '';
    } else {
        detail = info.KVDataList[_OpenDataCtx2.default.SCORE_INDEX].value || '';
    }
    return detail;
};

},{"./OpenDataCtx":6,"./Util":7}],6:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var OpenDataCtx = function OpenDataCtx() {
    _classCallCheck(this, OpenDataCtx);
};
/**描述信息，用于界面展示 */


exports.default = OpenDataCtx;
OpenDataCtx.DES_KEY = "detail";
/**用户数据更新时间 */
OpenDataCtx.UPDATE_TIME_KEY = 'updateTime';
/**用户当前获取的分数（这个很重要，用于排序） */
OpenDataCtx.SCORE_KEY = 'score';
/**用户的最高分 */
OpenDataCtx.SCORE_MAX_KEY = 'maxScore';
OpenDataCtx.keys = [OpenDataCtx.SCORE_KEY, OpenDataCtx.DES_KEY, OpenDataCtx.SCORE_MAX_KEY, OpenDataCtx.UPDATE_TIME_KEY];
OpenDataCtx.SCORE_INDEX = OpenDataCtx.keys.indexOf(OpenDataCtx.SCORE_KEY);
OpenDataCtx.DETAIL_INDEX = OpenDataCtx.keys.indexOf(OpenDataCtx.DES_KEY);

/**获取好友信息 */
OpenDataCtx.getFriendData = function (cb) {
    wx.getFriendCloudStorage({
        keyList: this.keys,
        success: cb
    });
};
/**获取群用户信息 */
OpenDataCtx.getGroupData = function (shareTicket, cb) {
    wx.getGroupCloudStorage({
        shareTicket: shareTicket,
        keyList: this.keys,
        success: cb
    });
};
/**获取用户数据 */
OpenDataCtx.getUserData = function (cb) {
    wx.getUserCloudStorage({
        keyList: this.keys,
        success: cb
    });
};
/**获取用户信息 */
OpenDataCtx.getUserInfo = function (users, cb) {
    wx.getUserInfo({
        openIdList: users,
        lang: "zh_CN",
        success: cb
    });
};
/**获取自己的信息 */
OpenDataCtx.getMyInfo = function (cb) {
    this.getUserInfo(["selfOpenId"], cb);
};

/**设置用户数据 */
OpenDataCtx.set = function (kvList) {
    //1、格式化数据
    kvList.forEach(function (element) {
        var value = element.value;
        if (typeof value != 'string') {
            console.error('\u5F53\u524D\u4F20\u5165\u6570\u636E\u683C\u5F0F\u6709\u8BEF:');
            console.error(JSON.stringify(element));
            element.value = String(value);
        }
    });
    var time = Date.now();
    var timeInterval = Number(time) / 1000;
    kvList.push({ key: this.UPDATE_TIME_KEY, value: timeInterval + "" });
    console.log('OD | SET | ' + JSON.stringify(kvList));
    wx.setUserCloudStorage({
        KVDataList: kvList,
        success: function success(res) {
            console.log("OD | SET | SUC | " + JSON.stringify(res));
        },
        fail: function fail(res) {
            console.log("OD | SET | FAIL | " + JSON.stringify(res));
        }
    });
};

/**移除用户数据 */
OpenDataCtx.remove = function (keys) {
    wx.removeUserCloudStorage({
        keyList: keys,
        success: function success(res) {
            console.log("OD | REMOVE | SUC | " + JSON.stringify(res));
        },
        fail: function fail(res) {
            console.log("OD | REMOVE | FAIL | " + JSON.stringify(res));
        }
    });
};

},{}],7:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var Util = function Util() {
    _classCallCheck(this, Util);
};

exports.default = Util;

Util.makeIcon = function (url) {
    var items = url.split("/") || [];
    if (items.length > 1) {
        var str = items[items.length - 1];
        items.pop();
        items.push("96");
        return items.join('/');
    }
    return this + "";
};
Util.formatName = function (name) {
    var n = 10;
    var str = name;
    var r = /[^\x00-\xff]/g;
    if (str.replace(r, "mm").length <= n) {
        return str + "";
    }
    var m = Math.floor(n / 2);
    for (var i = m; i < str.length; i++) {
        if (str.substring(0, i).replace(r, "mm").length >= n) {
            return str.substring(0, i) + "...";
        }
    }
    return str;
};
/**将obj的key的值，从一个数组，映射为一个对象 */
Util.flat = function (obj, key, map) {
    var list = obj[key];
    if (!list) {
        return;
    }
    list.forEach(function (element) {
        var key = element['key'];
        if (key) {
            if (obj[key]) {
                console.error(obj + "\u542B\u6709\u6307\u5B9A\u7684" + key);
            } else {
                obj[key] = element['value'];
            }
        } else {
            console.error(element + "\u4E0D\u5B58\u5728\u6307\u5B9A\u7684key");
        }
    });
};

},{}]},{},[2])
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uLy4uLy4uLy4uL0FwcGxpY2F0aW9ucy9MYXlhQWlySURFX2JldGEuYXBwL0NvbnRlbnRzL1Jlc291cmNlcy9hcHAvbm9kZV9tb2R1bGVzL2Jyb3dzZXItcGFjay9fcHJlbHVkZS5qcyIsInNyYy9HYW1lQ29uZmlnLmpzIiwic3JjL01haW4uanMiLCJzcmMvc2NyaXB0cy9jb21tb24vUmFua1NlcnZpY2UvUmFua0NlbGwuanMiLCJzcmMvc2NyaXB0cy9jb21tb24vUmFua1NlcnZpY2UvUmFua1ZpZXcuanMiLCJzcmMvc2NyaXB0cy91dGlscy9EYXRhQ2VudGVyLmpzIiwic3JjL3NjcmlwdHMvdXRpbHMvT3BlbkRhdGFDdHguanMiLCJzcmMvc2NyaXB0cy91dGlscy9VdGlsLmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7Ozs7Ozs7cWpCQ1ZBOzs7QUFDQTs7OztBQUNBOzs7Ozs7OztJQUVxQixVOzs7Ozs7OytCQUNIO0FBQ1Y7QUFDQSxnQkFBSSxNQUFNLEtBQUssVUFBTCxDQUFnQixRQUExQjtBQUNOLGdCQUFJLHdDQUFKLEVBQTZDLGtCQUE3QztBQUNBLGdCQUFJLHdDQUFKLEVBQTZDLGtCQUE3QztBQUNHOzs7Ozs7a0JBTmdCLFU7O0FBUXJCLFdBQVcsS0FBWCxHQUFtQixHQUFuQjtBQUNBLFdBQVcsTUFBWCxHQUFvQixJQUFwQjtBQUNBLFdBQVcsU0FBWCxHQUFzQixZQUF0QjtBQUNBLFdBQVcsVUFBWCxHQUF3QixNQUF4QjtBQUNBLFdBQVcsTUFBWCxHQUFvQixLQUFwQjtBQUNBLFdBQVcsTUFBWCxHQUFvQixNQUFwQjtBQUNBLFdBQVcsVUFBWCxHQUF3QixzQ0FBeEI7QUFDQSxXQUFXLFNBQVgsR0FBdUIsRUFBdkI7QUFDQSxXQUFXLEtBQVgsR0FBbUIsS0FBbkI7QUFDQSxXQUFXLElBQVgsR0FBa0IsS0FBbEI7QUFDQSxXQUFXLFlBQVgsR0FBMEIsS0FBMUI7QUFDQSxXQUFXLGlCQUFYLEdBQStCLElBQS9COztBQUVBLFdBQVcsSUFBWDs7Ozs7OztBQ3pCQTs7OztBQUNBOzs7Ozs7OztJQUNNLEk7QUFDTCxpQkFBYztBQUFBOztBQUNiLE9BQUssVUFBTCxHQUFrQixJQUFsQjtBQUNBLE9BQUssbUJBQUwsR0FBMkIsSUFBM0I7QUFDQSxPQUFLLElBQUwsQ0FBVSxHQUFWLEVBQWUsSUFBZjtBQUNBLE9BQUssS0FBTCxDQUFXLFNBQVgsR0FBdUIsS0FBSyxLQUFMLENBQVcsaUJBQWxDO0FBQ0EsT0FBSyxLQUFMLENBQVcsVUFBWCxHQUF3QixLQUFLLEtBQUwsQ0FBVyxlQUFuQztBQUNBLE9BQUssS0FBTCxDQUFXLE1BQVgsR0FBb0IsS0FBSyxLQUFMLENBQVcsWUFBL0I7QUFDQSxPQUFLLEtBQUwsQ0FBVyxNQUFYLEdBQW9CLEtBQUssS0FBTCxDQUFXLFlBQS9CO0FBQ0E7QUFDQSxPQUFLLEdBQUwsQ0FBUyxpQkFBVCxHQUE2QixJQUE3QjtBQUNBOzs7OzRCQUNTLEUsRUFBSTtBQUNiLFFBQUssTUFBTCxDQUFZLElBQVosQ0FBaUIsNkJBQWpCLEVBQWdELEtBQUssT0FBTCxDQUFhLE1BQWIsQ0FBb0IsSUFBcEIsRUFBMEIsVUFBVSxJQUFWLEVBQWdCO0FBQ3pGLFNBQUssS0FBTCxDQUFXLElBQVgsQ0FBZ0Isc0NBQWhCLEVBQXdELElBQXhELEVBQThELElBQTlELEVBQW9FLEtBQUssT0FBTCxDQUFhLE1BQWIsQ0FBb0IsSUFBcEIsRUFBMEIsVUFBVSxLQUFWLEVBQWlCO0FBQzlHLFFBQUcsS0FBSDtBQUNBLEtBRm1FLENBQXBFO0FBR0EsSUFKK0MsQ0FBaEQ7QUFLQTs7Ozs7O0FBR0Y7OztBQUNBLElBQUksT0FBTyxJQUFJLElBQUosRUFBWDs7QUFFQSxJQUFJLE9BQU8sRUFBWCxFQUFlO0FBQ2QsSUFBRyxTQUFILENBQWEsVUFBVSxJQUFWLEVBQWdCO0FBQzVCLFVBQVEsS0FBSyxJQUFiO0FBQ0MsUUFBSyxjQUFMO0FBQ0MseUJBQVcsaUJBQVgsQ0FBNkIsVUFBQyxJQUFELEVBQU8sSUFBUCxFQUFnQjtBQUM1QyxVQUFLLFNBQUwsQ0FBZSxVQUFTLEtBQVQsRUFBZTtBQUM3QixZQUFNLFdBQU4sQ0FBa0IsSUFBbEIsRUFBd0IsSUFBeEI7QUFDQSxNQUZEO0FBR0EsS0FKRDtBQUtBO0FBQ0QsUUFBSyxtQkFBTDtBQUNDLFFBQUksY0FBYyxLQUFLLFdBQXZCO0FBQ0EseUJBQVcsZ0JBQVgsQ0FBNEIsV0FBNUIsRUFBeUMsVUFBQyxJQUFELEVBQU8sSUFBUCxFQUFnQjtBQUN4RCxVQUFLLFNBQUwsQ0FBZSxVQUFTLEtBQVQsRUFBZTtBQUM3QixZQUFNLFdBQU4sQ0FBa0IsSUFBbEIsRUFBd0IsSUFBeEI7QUFDQSxNQUZEO0FBR0EsS0FKRDtBQUtBO0FBZkY7QUFpQkEsRUFsQkQ7QUFtQkE7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDOUNvQixROzs7Ozs7Ozs7OztrQ0FDUjtBQUNMLGlCQUFLLE9BQUwsR0FBZSxLQUFLLGNBQUwsQ0FBb0IsU0FBcEIsQ0FBZjtBQUNBLGlCQUFLLE9BQUwsR0FBZSxLQUFLLGNBQUwsQ0FBb0IsU0FBcEIsQ0FBZjtBQUNBLGlCQUFLLE9BQUwsR0FBZSxLQUFLLGNBQUwsQ0FBb0IsU0FBcEIsQ0FBZjtBQUNBLGlCQUFLLFFBQUwsR0FBZ0IsS0FBSyxjQUFMLENBQW9CLFVBQXBCLENBQWhCO0FBQ0g7OztnQ0FDTyxJLEVBQUs7QUFDVCxpQkFBSyxPQUFMLENBQWEsSUFBYixHQUFvQixLQUFLLElBQXpCO0FBQ0EsaUJBQUssT0FBTCxDQUFhLElBQWIsR0FBb0IsS0FBSyxTQUF6QjtBQUNBLGlCQUFLLE9BQUwsQ0FBYSxJQUFiLEdBQW9CLEtBQUssUUFBekI7QUFDQSxpQkFBSyxRQUFMLENBQWMsSUFBZCxHQUFxQixLQUFLLE1BQTFCO0FBQ0g7Ozs7RUFaaUMsS0FBSyxHOztrQkFBdEIsUTs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQSxROzs7Ozs7Ozs7OztrQ0FDUjtBQUNMLGlCQUFLLGNBQUw7QUFDSDs7O3lDQUNlO0FBQ1osZ0JBQUksV0FBVyxLQUFLLFFBQXBCO0FBQ0EscUJBQVMsY0FBVCxHQUEwQixFQUExQjtBQUNBLHFCQUFTLGFBQVQsR0FBMEIsS0FBSyxPQUFMLENBQWEsTUFBYixDQUFvQixJQUFwQixFQUF5QixVQUFTLElBQVQsRUFBYyxLQUFkLEVBQW9CO0FBQ25FLG9CQUFJLE9BQU8sU0FBUyxLQUFULENBQWUsS0FBZixDQUFYO0FBQ0EscUJBQUssT0FBTCxDQUFhLElBQWI7QUFDQSxvQkFBSSxTQUFTLENBQWIsRUFBZ0I7QUFDWix5QkFBSyxPQUFMLENBQWEsS0FBYixHQUFxQixTQUFyQjtBQUNBLHlCQUFLLE9BQUwsQ0FBYSxJQUFiLEdBQW9CLElBQXBCO0FBQ0gsaUJBSEQsTUFHTyxJQUFJLFNBQVMsQ0FBVCxJQUFjLFNBQVMsQ0FBM0IsRUFBNkI7QUFDaEMseUJBQUssT0FBTCxDQUFhLEtBQWIsR0FBcUIsU0FBckI7QUFDQSx5QkFBSyxPQUFMLENBQWEsSUFBYixHQUFvQixJQUFwQjtBQUNILGlCQUhNLE1BR0E7QUFDSCx5QkFBSyxPQUFMLENBQWEsS0FBYixHQUFxQixTQUFyQjtBQUNBLHlCQUFLLE9BQUwsQ0FBYSxJQUFiLEdBQW9CLEtBQXBCO0FBQ0g7QUFDSixhQWJ5QixFQWF4QixJQWJ3QixFQWFuQixLQWJtQixDQUExQjtBQWNIOzs7bUNBQ1UsSSxFQUFLO0FBQ1osaUJBQUssUUFBTCxDQUFjLE9BQWQsR0FBd0IsS0FBSyxNQUFMLEdBQWMsQ0FBZCxHQUFrQixDQUFsQixHQUFvQixLQUFLLE1BQWpEO0FBQ0EsaUJBQUssUUFBTCxDQUFjLEtBQWQsR0FBc0IsSUFBdEI7QUFDQSxpQkFBSyxRQUFMLENBQWMsT0FBZDtBQUNIOzs7NkNBQ29CLEksRUFBSztBQUN0QixpQkFBSyxVQUFMLENBQWdCLE9BQWhCLENBQXdCLElBQXhCO0FBQ0g7OztvQ0FDVyxJLEVBQUssSSxFQUFLO0FBQ2xCLGlCQUFLLFVBQUwsQ0FBZ0IsSUFBaEI7QUFDQSxpQkFBSyxvQkFBTCxDQUEwQixJQUExQjtBQUNIOzs7O0VBakNpQyxLQUFLLEk7O2tCQUF0QixROzs7Ozs7Ozs7QUNBckI7Ozs7QUFDQTs7Ozs7Ozs7SUFDcUIsVTs7O0FBR3JCOzs7a0JBSHFCLFU7QUFJckIsV0FBVyxXQUFYLEdBQXlCLElBQXpCO0FBQ0E7QUFDQSxXQUFXLE1BQVgsR0FBb0IsSUFBcEI7QUFDQTtBQUNBLFdBQVcsSUFBWCxHQUFrQixJQUFsQjtBQUNBOzs7Ozs7OztBQVFBLFdBQVcsUUFBWCxHQUFzQixVQUFVLElBQVYsRUFBZ0IsRUFBaEIsRUFBb0I7QUFBQTs7QUFDdEMsUUFBSSxPQUFPLEtBQUssVUFBTCxDQUFnQixJQUFoQixDQUFYO0FBQ0EsU0FBSyxlQUFMLENBQXFCLFVBQUMsSUFBRCxFQUFVO0FBQzNCLGFBQUssSUFBTCxHQUFZLE1BQUssWUFBTCxDQUFrQixJQUFsQixFQUF3QixJQUF4QixDQUFaO0FBQ0EsYUFBSyxNQUFMLEdBQWMsTUFBSyxjQUFMLENBQW9CLElBQXBCLENBQWQ7QUFDQSxjQUFNLEdBQUcsSUFBSCxFQUFTLElBQVQsQ0FBTjtBQUNILEtBSkQ7QUFLSCxDQVBEO0FBUUEsV0FBVyxpQkFBWCxHQUErQixVQUFVLEVBQVYsRUFBYztBQUFBOztBQUN6QywwQkFBWSxhQUFaLENBQTBCLFVBQUMsR0FBRCxFQUFTO0FBQy9CLGVBQUssUUFBTCxDQUFjLElBQUksSUFBbEIsRUFBd0IsRUFBeEI7QUFDSCxLQUZEO0FBR0gsQ0FKRDtBQUtBLFdBQVcsZ0JBQVgsR0FBOEIsVUFBVSxXQUFWLEVBQXVCLEVBQXZCLEVBQTJCO0FBQUE7O0FBQ3JELDBCQUFZLFlBQVosQ0FBeUIsV0FBekIsRUFBc0MsVUFBQyxHQUFELEVBQVM7QUFDM0MsZUFBSyxRQUFMLENBQWMsSUFBSSxJQUFsQixFQUF3QixFQUF4QjtBQUNILEtBRkQ7QUFHSCxDQUpEO0FBS0E7QUFDQSxXQUFXLGNBQVgsR0FBNEIsVUFBVSxNQUFWLEVBQWtCO0FBQzFDLFFBQUksQ0FBQyxPQUFPLHNCQUFZLFNBQW5CLENBQUwsRUFBb0M7QUFDaEMsZ0JBQVEsS0FBUixDQUFjLFdBQWQ7QUFDQTtBQUNIO0FBQ0QsUUFBSSxTQUFTLEVBQWI7O0FBRUEsUUFBSSxTQUFTLFdBQVcsTUFBeEI7QUFDQSxRQUFJLFNBQVMsT0FBTyxNQUFwQjtBQUNBLFFBQUksQ0FBQyxNQUFMLEVBQWE7QUFBRTtBQUFRO0FBQ3ZCLFFBQUksUUFBUSxPQUFPLHNCQUFZLFNBQW5CLENBQVo7QUFDQSxRQUFJLFdBQVcsT0FBTyxzQkFBWSxhQUFuQixDQUFmO0FBQ0EsZUFBVyxLQUFLLEdBQUwsQ0FBUyxRQUFULEVBQW1CLEtBQW5CLENBQVg7O0FBRUEsV0FBTyxJQUFQLENBQVk7QUFDUixhQUFLLHNCQUFZLFNBRFQ7QUFFUixlQUFPLFdBQVc7QUFGVixLQUFaO0FBSUEsV0FBTyxJQUFQLENBQVk7QUFDUixhQUFLLHNCQUFZLGFBRFQ7QUFFUixlQUFPLFdBQVc7QUFGVixLQUFaOztBQUtBLFFBQUksT0FBTyxzQkFBWSxPQUFuQixDQUFKLEVBQWlDO0FBQzdCLGVBQU8sSUFBUCxDQUFZO0FBQ1IsaUJBQUssc0JBQVksT0FEVDtBQUVSLG1CQUFPLE9BQU8sc0JBQVksT0FBbkI7QUFGQyxTQUFaO0FBSUgsS0FMRCxNQUtPO0FBQ0gsZUFBTyxJQUFQLENBQVk7QUFDUixpQkFBSyxzQkFBWSxPQURUO0FBRVIsbUJBQU8sV0FBVyxPQUFPLE1BQVA7QUFGVixTQUFaO0FBSUg7QUFDRCwwQkFBWSxHQUFaLENBQWdCLE1BQWhCO0FBQ0gsQ0FuQ0Q7QUFvQ0E7QUFDQSxXQUFXLGFBQVgsR0FBMkIsVUFBVSxFQUFWLEVBQWM7QUFBQTs7QUFDckMsUUFBSSxLQUFLLElBQVQsRUFBZTtBQUFFLGNBQU0sR0FBRyxLQUFLLElBQVIsQ0FBTjtBQUFxQjtBQUN0QywwQkFBWSxTQUFaLENBQXNCLFVBQUMsR0FBRCxFQUFTO0FBQzNCLFlBQUksT0FBTyxJQUFJLElBQUosQ0FBUyxDQUFULENBQVg7QUFDQSxhQUFLLFFBQUwsR0FBZ0IsZUFBSyxVQUFMLENBQWdCLEtBQUssUUFBckIsQ0FBaEI7QUFDQSxhQUFLLFNBQUwsR0FBaUIsZUFBSyxRQUFMLENBQWMsS0FBSyxTQUFuQixDQUFqQjtBQUNBLGVBQUssSUFBTCxHQUFZLElBQVo7QUFDQSxjQUFNLEdBQUcsT0FBSyxJQUFSLENBQU47QUFDSCxLQU5EO0FBT0gsQ0FURDtBQVVBLFdBQVcsZUFBWCxHQUE2QixVQUFVLEVBQVYsRUFBYztBQUN2QyxTQUFLLGFBQUwsQ0FBbUIsVUFBQyxJQUFELEVBQVU7QUFDekIsOEJBQVksV0FBWixDQUF3QixVQUFDLEdBQUQsRUFBUztBQUM3QixnQkFBSSxPQUFPO0FBQ1Asd0JBQVEsRUFERDtBQUVQLDBCQUFVLEtBQUssUUFGUjtBQUdQLDJCQUFXLEtBQUssU0FIVDtBQUlQLDRCQUFZLElBQUk7QUFKVCxhQUFYO0FBTUEsa0JBQU0sR0FBRyxJQUFILENBQU47QUFDSCxTQVJEO0FBU0gsS0FWRDtBQVdILENBWkQ7O0FBY0EsV0FBVyxVQUFYLEdBQXdCLFVBQVUsSUFBVixFQUFnQjtBQUFBOztBQUNwQyxRQUFJLFNBQVMsRUFBYjtBQUNBLFNBQUssSUFBSSxJQUFJLENBQVIsRUFBVyxTQUFTLEtBQUssTUFBOUIsRUFBc0MsSUFBSSxNQUExQyxFQUFrRCxHQUFsRCxFQUF1RDtBQUNuRCxZQUFJLE9BQU8sS0FBSyxDQUFMLENBQVg7QUFDQSxZQUFJLFNBQVMsS0FBSyxVQUFsQjtBQUNBLFlBQUksQ0FBQyxNQUFELElBQVcsT0FBTyxNQUFQLElBQWlCLENBQWhDLEVBQW1DO0FBQy9CLG9CQUFRLEtBQVIsQ0FBYyxxQkFBZDtBQUNBLG9CQUFRLEdBQVIsQ0FBWSxLQUFLLFNBQUwsQ0FBZSxJQUFmLENBQVo7QUFDQTtBQUNIO0FBQ0Q7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBRUEsYUFBSyxRQUFMLEdBQWdCLGVBQUssVUFBTCxDQUFnQixLQUFLLFFBQXJCLENBQWhCO0FBQ0EsYUFBSyxTQUFMLEdBQWlCLGVBQUssUUFBTCxDQUFjLEtBQUssU0FBbkIsQ0FBakI7QUFDQSxlQUFPLElBQVAsQ0FBWSxJQUFaO0FBQ0g7QUFDRCxXQUFPLE9BQVAsQ0FBZSxVQUFDLElBQUQsRUFBTyxHQUFQLEVBQWU7QUFDMUIsYUFBSyxJQUFMLFlBQWtCLE1BQU0sQ0FBeEI7QUFDQSxhQUFLLE1BQUwsR0FBYyxPQUFLLGNBQUwsQ0FBb0IsSUFBcEIsQ0FBZDtBQUNILEtBSEQ7QUFJQSxXQUFPLElBQVAsQ0FBWSxVQUFDLEdBQUQsRUFBTSxHQUFOLEVBQWM7QUFDdEIsZUFBTyxJQUFJLFVBQUosQ0FBZSxzQkFBWSxXQUEzQixFQUF3QyxLQUF4QyxHQUFnRCxJQUFJLFVBQUosQ0FBZSxzQkFBWSxXQUEzQixFQUF3QyxLQUEvRjtBQUNILEtBRkQ7QUFHQSxXQUFPLE1BQVA7QUFDSCxDQTdCRDtBQThCQSxXQUFXLFlBQVgsR0FBMEIsVUFBVSxJQUFWLEVBQWdCLElBQWhCLEVBQXNCO0FBQzVDLFFBQUksV0FBVyxDQUFDLENBQWhCO0FBQ0EsU0FBSyxJQUFJLElBQUksQ0FBYixFQUFnQixJQUFJLEtBQUssTUFBekIsRUFBaUMsR0FBakMsRUFBc0M7QUFDbEMsWUFBSSxPQUFPLEtBQUssQ0FBTCxDQUFYO0FBQ0EsWUFBSSxLQUFLLFNBQUwsSUFBa0IsS0FBSyxTQUF2QixJQUFvQyxLQUFLLFFBQUwsSUFBaUIsS0FBSyxRQUE5RCxFQUF3RTtBQUNwRSx1QkFBVyxDQUFYO0FBQ0g7QUFDRCxhQUFLLElBQUwsR0FBWSxTQUFTLElBQUksQ0FBYixDQUFaO0FBQ0g7QUFDRCxXQUFRLFlBQVksQ0FBQyxDQUFkLEdBQW1CLEtBQW5CLEdBQTRCLFNBQVMsV0FBVyxDQUFwQixDQUFuQztBQUNILENBVkQ7QUFXQSxXQUFXLGNBQVgsR0FBNEIsVUFBVSxJQUFWLEVBQWdCO0FBQ3hDLFFBQUksU0FBUyxFQUFiO0FBQ0EsUUFBSSxLQUFLLFVBQUwsQ0FBZ0IsTUFBaEIsR0FBeUIsc0JBQVksWUFBekMsRUFBdUQ7QUFDbkQsaUJBQVMsS0FBSyxVQUFMLENBQWdCLHNCQUFZLFlBQTVCLEVBQTBDLEtBQTFDLElBQW1ELEtBQUssVUFBTCxDQUFnQixzQkFBWSxXQUE1QixFQUF5QyxLQUE1RixJQUFxRyxFQUE5RztBQUNILEtBRkQsTUFFTztBQUNILGlCQUFTLEtBQUssVUFBTCxDQUFnQixzQkFBWSxXQUE1QixFQUF5QyxLQUF6QyxJQUFrRCxFQUEzRDtBQUNIO0FBQ0QsV0FBTyxNQUFQO0FBQ0gsQ0FSRDs7Ozs7Ozs7Ozs7SUM1SXFCLFc7OztBQUlyQjs7O2tCQUpxQixXO0FBS3JCLFlBQVksT0FBWixHQUFzQixRQUF0QjtBQUNBO0FBQ0EsWUFBWSxlQUFaLEdBQThCLFlBQTlCO0FBQ0E7QUFDQSxZQUFZLFNBQVosR0FBd0IsT0FBeEI7QUFDQTtBQUNBLFlBQVksYUFBWixHQUE0QixVQUE1QjtBQUNBLFlBQVksSUFBWixHQUFtQixDQUNmLFlBQVksU0FERyxFQUVmLFlBQVksT0FGRyxFQUdmLFlBQVksYUFIRyxFQUlmLFlBQVksZUFKRyxDQUFuQjtBQU1BLFlBQVksV0FBWixHQUEwQixZQUFZLElBQVosQ0FBaUIsT0FBakIsQ0FBeUIsWUFBWSxTQUFyQyxDQUExQjtBQUNBLFlBQVksWUFBWixHQUEyQixZQUFZLElBQVosQ0FBaUIsT0FBakIsQ0FBeUIsWUFBWSxPQUFyQyxDQUEzQjs7QUFFQTtBQUNBLFlBQVksYUFBWixHQUE0QixVQUFVLEVBQVYsRUFBYztBQUN0QyxPQUFHLHFCQUFILENBQXlCO0FBQ3JCLGlCQUFTLEtBQUssSUFETztBQUVyQixpQkFBUztBQUZZLEtBQXpCO0FBSUgsQ0FMRDtBQU1BO0FBQ0EsWUFBWSxZQUFaLEdBQTJCLFVBQVUsV0FBVixFQUF1QixFQUF2QixFQUEyQjtBQUNsRCxPQUFHLG9CQUFILENBQXdCO0FBQ3BCLHFCQUFhLFdBRE87QUFFcEIsaUJBQVMsS0FBSyxJQUZNO0FBR3BCLGlCQUFTO0FBSFcsS0FBeEI7QUFLSCxDQU5EO0FBT0E7QUFDQSxZQUFZLFdBQVosR0FBMEIsVUFBVSxFQUFWLEVBQWM7QUFDcEMsT0FBRyxtQkFBSCxDQUF1QjtBQUNuQixpQkFBUyxLQUFLLElBREs7QUFFbkIsaUJBQVM7QUFGVSxLQUF2QjtBQUlILENBTEQ7QUFNQTtBQUNBLFlBQVksV0FBWixHQUEwQixVQUFVLEtBQVYsRUFBaUIsRUFBakIsRUFBcUI7QUFDM0MsT0FBRyxXQUFILENBQWU7QUFDWCxvQkFBWSxLQUREO0FBRVgsY0FBTSxPQUZLO0FBR1gsaUJBQVM7QUFIRSxLQUFmO0FBS0gsQ0FORDtBQU9BO0FBQ0EsWUFBWSxTQUFaLEdBQXdCLFVBQVUsRUFBVixFQUFjO0FBQ2xDLFNBQUssV0FBTCxDQUFpQixDQUFDLFlBQUQsQ0FBakIsRUFBaUMsRUFBakM7QUFDSCxDQUZEOztBQUlBO0FBQ0EsWUFBWSxHQUFaLEdBQWtCLFVBQVUsTUFBVixFQUFrQjtBQUNoQztBQUNBLFdBQU8sT0FBUCxDQUFlLG1CQUFXO0FBQ3RCLFlBQUksUUFBUSxRQUFRLEtBQXBCO0FBQ0EsWUFBSSxPQUFPLEtBQVAsSUFBZ0IsUUFBcEIsRUFBOEI7QUFDMUIsb0JBQVEsS0FBUjtBQUNBLG9CQUFRLEtBQVIsQ0FBYyxLQUFLLFNBQUwsQ0FBZSxPQUFmLENBQWQ7QUFDQSxvQkFBUSxLQUFSLEdBQWdCLE9BQU8sS0FBUCxDQUFoQjtBQUNIO0FBQ0osS0FQRDtBQVFBLFFBQUksT0FBTyxLQUFLLEdBQUwsRUFBWDtBQUNBLFFBQUksZUFBZSxPQUFPLElBQVAsSUFBZSxJQUFsQztBQUNBLFdBQU8sSUFBUCxDQUFZLEVBQUUsS0FBSyxLQUFLLGVBQVosRUFBNkIsT0FBTyxlQUFlLEVBQW5ELEVBQVo7QUFDQSxZQUFRLEdBQVIsaUJBQTBCLEtBQUssU0FBTCxDQUFlLE1BQWYsQ0FBMUI7QUFDQSxPQUFHLG1CQUFILENBQXVCO0FBQ25CLG9CQUFZLE1BRE87QUFFbkIsZUFGbUIsbUJBRVgsR0FGVyxFQUVOO0FBQ1Qsb0JBQVEsR0FBUixDQUFZLHNCQUFzQixLQUFLLFNBQUwsQ0FBZSxHQUFmLENBQWxDO0FBQ0gsU0FKa0I7QUFLbkIsWUFMbUIsZ0JBS2QsR0FMYyxFQUtUO0FBQ04sb0JBQVEsR0FBUixDQUFZLHVCQUF1QixLQUFLLFNBQUwsQ0FBZSxHQUFmLENBQW5DO0FBQ0g7QUFQa0IsS0FBdkI7QUFTSCxDQXZCRDs7QUF5QkE7QUFDQSxZQUFZLE1BQVosR0FBcUIsVUFBVSxJQUFWLEVBQWdCO0FBQ2pDLE9BQUcsc0JBQUgsQ0FBMEI7QUFDdEIsaUJBQVMsSUFEYTtBQUV0QixlQUZzQixtQkFFZCxHQUZjLEVBRVQ7QUFDVCxvQkFBUSxHQUFSLENBQVkseUJBQXlCLEtBQUssU0FBTCxDQUFlLEdBQWYsQ0FBckM7QUFDSCxTQUpxQjtBQUt0QixZQUxzQixnQkFLakIsR0FMaUIsRUFLWjtBQUNOLG9CQUFRLEdBQVIsQ0FBWSwwQkFBMEIsS0FBSyxTQUFMLENBQWUsR0FBZixDQUF0QztBQUNIO0FBUHFCLEtBQTFCO0FBU0gsQ0FWRDs7Ozs7Ozs7Ozs7SUNuRnFCLEk7Ozs7a0JBQUEsSTs7QUFHckIsS0FBSyxRQUFMLEdBQWdCLFVBQVUsR0FBVixFQUFlO0FBQzNCLFFBQUksUUFBUSxJQUFJLEtBQUosQ0FBVSxHQUFWLEtBQWtCLEVBQTlCO0FBQ0EsUUFBSSxNQUFNLE1BQU4sR0FBZSxDQUFuQixFQUFzQjtBQUNsQixZQUFJLE1BQU0sTUFBTSxNQUFNLE1BQU4sR0FBZSxDQUFyQixDQUFWO0FBQ0EsY0FBTSxHQUFOO0FBQ0EsY0FBTSxJQUFOLENBQVcsSUFBWDtBQUNBLGVBQU8sTUFBTSxJQUFOLENBQVcsR0FBWCxDQUFQO0FBQ0g7QUFDRCxXQUFPLE9BQU8sRUFBZDtBQUNILENBVEQ7QUFVQSxLQUFLLFVBQUwsR0FBa0IsVUFBVSxJQUFWLEVBQWdCO0FBQzlCLFFBQUksSUFBSSxFQUFSO0FBQ0EsUUFBSSxNQUFNLElBQVY7QUFDQSxRQUFJLElBQUksZUFBUjtBQUNBLFFBQUksSUFBSSxPQUFKLENBQVksQ0FBWixFQUFlLElBQWYsRUFBcUIsTUFBckIsSUFBK0IsQ0FBbkMsRUFBc0M7QUFDbEMsZUFBTyxNQUFNLEVBQWI7QUFDSDtBQUNELFFBQUksSUFBSSxLQUFLLEtBQUwsQ0FBVyxJQUFJLENBQWYsQ0FBUjtBQUNBLFNBQUssSUFBSSxJQUFJLENBQWIsRUFBZ0IsSUFBSSxJQUFJLE1BQXhCLEVBQWdDLEdBQWhDLEVBQXFDO0FBQ2pDLFlBQUksSUFBSSxTQUFKLENBQWMsQ0FBZCxFQUFpQixDQUFqQixFQUFvQixPQUFwQixDQUE0QixDQUE1QixFQUErQixJQUEvQixFQUFxQyxNQUFyQyxJQUErQyxDQUFuRCxFQUFzRDtBQUNsRCxtQkFBTyxJQUFJLFNBQUosQ0FBYyxDQUFkLEVBQWlCLENBQWpCLElBQXNCLEtBQTdCO0FBQ0g7QUFDSjtBQUNELFdBQU8sR0FBUDtBQUNILENBZEQ7QUFlQTtBQUNBLEtBQUssSUFBTCxHQUFZLFVBQVUsR0FBVixFQUFlLEdBQWYsRUFBb0IsR0FBcEIsRUFBeUI7QUFDakMsUUFBSSxPQUFPLElBQUksR0FBSixDQUFYO0FBQ0EsUUFBSSxDQUFDLElBQUwsRUFBVztBQUFFO0FBQVE7QUFDckIsU0FBSyxPQUFMLENBQWEsbUJBQVc7QUFDcEIsWUFBSSxNQUFNLFFBQVEsS0FBUixDQUFWO0FBQ0EsWUFBSSxHQUFKLEVBQVM7QUFDTCxnQkFBSSxJQUFJLEdBQUosQ0FBSixFQUFjO0FBQ1Ysd0JBQVEsS0FBUixDQUFpQixHQUFqQixzQ0FBNEIsR0FBNUI7QUFDSCxhQUZELE1BRU87QUFDSCxvQkFBSSxHQUFKLElBQVcsUUFBUSxPQUFSLENBQVg7QUFDSDtBQUNKLFNBTkQsTUFNTztBQUNILG9CQUFRLEtBQVIsQ0FBaUIsT0FBakI7QUFDSDtBQUNKLEtBWEQ7QUFZSCxDQWZEIiwiZmlsZSI6ImdlbmVyYXRlZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzQ29udGVudCI6WyJ2YXIgX19leHRlbmRzID0gKHRoaXMgJiYgdGhpcy5fX2V4dGVuZHMpIHx8IChmdW5jdGlvbiAoKSB7XHJcbiAgICB2YXIgZXh0ZW5kU3RhdGljcyA9IE9iamVjdC5zZXRQcm90b3R5cGVPZiB8fFxyXG4gICAgICAgICh7IF9fcHJvdG9fXzogW10gfSBpbnN0YW5jZW9mIEFycmF5ICYmIGZ1bmN0aW9uIChkLCBiKSB7IGQuX19wcm90b19fID0gYjsgfSkgfHxcclxuICAgICAgICBmdW5jdGlvbiAoZCwgYikgeyBmb3IgKHZhciBwIGluIGIpIGlmIChiLmhhc093blByb3BlcnR5KHApKSBkW3BdID0gYltwXTsgfTtcclxuICAgIHJldHVybiBmdW5jdGlvbiAoZCwgYikge1xyXG4gICAgICAgIGV4dGVuZFN0YXRpY3MoZCwgYik7XHJcbiAgICAgICAgZnVuY3Rpb24gX18oKSB7IHRoaXMuY29uc3RydWN0b3IgPSBkOyB9XHJcbiAgICAgICAgZC5wcm90b3R5cGUgPSBiID09PSBudWxsID8gT2JqZWN0LmNyZWF0ZShiKSA6IChfXy5wcm90b3R5cGUgPSBiLnByb3RvdHlwZSwgbmV3IF9fKCkpO1xyXG4gICAgfTtcclxufSkoKTtcclxuKGZ1bmN0aW9uKCl7ZnVuY3Rpb24gcihlLG4sdCl7ZnVuY3Rpb24gbyhpLGYpe2lmKCFuW2ldKXtpZighZVtpXSl7dmFyIGM9XCJmdW5jdGlvblwiPT10eXBlb2YgcmVxdWlyZSYmcmVxdWlyZTtpZighZiYmYylyZXR1cm4gYyhpLCEwKTtpZih1KXJldHVybiB1KGksITApO3ZhciBhPW5ldyBFcnJvcihcIkNhbm5vdCBmaW5kIG1vZHVsZSAnXCIraStcIidcIik7dGhyb3cgYS5jb2RlPVwiTU9EVUxFX05PVF9GT1VORFwiLGF9dmFyIHA9bltpXT17ZXhwb3J0czp7fX07ZVtpXVswXS5jYWxsKHAuZXhwb3J0cyxmdW5jdGlvbihyKXt2YXIgbj1lW2ldWzFdW3JdO3JldHVybiBvKG58fHIpfSxwLHAuZXhwb3J0cyxyLGUsbix0KX1yZXR1cm4gbltpXS5leHBvcnRzfWZvcih2YXIgdT1cImZ1bmN0aW9uXCI9PXR5cGVvZiByZXF1aXJlJiZyZXF1aXJlLGk9MDtpPHQubGVuZ3RoO2krKylvKHRbaV0pO3JldHVybiBvfXJldHVybiByfSkoKSIsIi8qKlRoaXMgY2xhc3MgaXMgYXV0b21hdGljYWxseSBnZW5lcmF0ZWQgYnkgTGF5YUFpcklERSwgcGxlYXNlIGRvIG5vdCBtYWtlIGFueSBtb2RpZmljYXRpb25zLiAqL1xyXG5pbXBvcnQgUmFua1ZpZXcgZnJvbSBcIi4vc2NyaXB0cy9jb21tb24vUmFua1NlcnZpY2UvUmFua1ZpZXdcIlxuaW1wb3J0IFJhbmtDZWxsIGZyb20gXCIuL3NjcmlwdHMvY29tbW9uL1JhbmtTZXJ2aWNlL1JhbmtDZWxsXCJcclxuXHJcbmV4cG9ydCBkZWZhdWx0IGNsYXNzIEdhbWVDb25maWcge1xyXG4gICAgc3RhdGljIGluaXQoKSB7XHJcbiAgICAgICAgLy/ms6jlhoxTY3JpcHTmiJbogIVSdW50aW1l5byV55SoXHJcbiAgICAgICAgbGV0IHJlZyA9IExheWEuQ2xhc3NVdGlscy5yZWdDbGFzcztcclxuXHRcdHJlZyhcInNjcmlwdHMvY29tbW9uL1JhbmtTZXJ2aWNlL1JhbmtWaWV3LmpzXCIsUmFua1ZpZXcpO1xuXHRcdHJlZyhcInNjcmlwdHMvY29tbW9uL1JhbmtTZXJ2aWNlL1JhbmtDZWxsLmpzXCIsUmFua0NlbGwpO1xyXG4gICAgfVxyXG59XHJcbkdhbWVDb25maWcud2lkdGggPSA2NDA7XHJcbkdhbWVDb25maWcuaGVpZ2h0ID0gMTEzNjtcclxuR2FtZUNvbmZpZy5zY2FsZU1vZGUgPVwiZml4ZWR3aWR0aFwiO1xyXG5HYW1lQ29uZmlnLnNjcmVlbk1vZGUgPSBcIm5vbmVcIjtcclxuR2FtZUNvbmZpZy5hbGlnblYgPSBcInRvcFwiO1xyXG5HYW1lQ29uZmlnLmFsaWduSCA9IFwibGVmdFwiO1xyXG5HYW1lQ29uZmlnLnN0YXJ0U2NlbmUgPSBcInNjZW5lcy9jb21tb24vUmFuay9PRENSYW5rVmlldy5zY2VuZVwiO1xyXG5HYW1lQ29uZmlnLnNjZW5lUm9vdCA9IFwiXCI7XHJcbkdhbWVDb25maWcuZGVidWcgPSBmYWxzZTtcclxuR2FtZUNvbmZpZy5zdGF0ID0gZmFsc2U7XHJcbkdhbWVDb25maWcucGh5c2ljc0RlYnVnID0gZmFsc2U7XHJcbkdhbWVDb25maWcuZXhwb3J0U2NlbmVUb0pzb24gPSB0cnVlO1xyXG5cclxuR2FtZUNvbmZpZy5pbml0KCk7XHJcbiIsImltcG9ydCBHYW1lQ29uZmlnIGZyb20gXCIuL0dhbWVDb25maWdcIjtcclxuaW1wb3J0IERhdGFDZW50ZXIgZnJvbSBcIi4vc2NyaXB0cy91dGlscy9EYXRhQ2VudGVyXCI7XHJcbmNsYXNzIE1haW4ge1xyXG5cdGNvbnN0cnVjdG9yKCkge1xyXG5cdFx0TGF5YS5pc1dYUG9zTXNnID0gdHJ1ZVxyXG5cdFx0TGF5YS5pc1dYT3BlbkRhdGFDb250ZXh0ID0gdHJ1ZVxyXG5cdFx0TGF5YS5pbml0KDc1MCwgMTMzNClcclxuXHRcdExheWEuc3RhZ2Uuc2NhbGVNb2RlID0gTGF5YS5TdGFnZS5TQ0FMRV9GSVhFRF9XSURUSFxyXG5cdFx0TGF5YS5zdGFnZS5zY3JlZW5Nb2RlID0gTGF5YS5TdGFnZS5TQ1JFRU5fVkVSVElDQUxcclxuXHRcdExheWEuc3RhZ2UuYWxpZ25WID0gTGF5YS5TdGFnZS5BTElHTl9NSURETEVcclxuXHRcdExheWEuc3RhZ2UuYWxpZ25IID0gTGF5YS5TdGFnZS5BTElHTl9DRU5URVJcclxuXHRcdC8v5YW85a655b6u5L+h5LiN5pSv5oyB5Yqg6L29c2NlbmXlkI7nvIDlnLrmma9cclxuXHRcdExheWEuVVJMLmV4cG9ydFNjZW5lVG9Kc29uID0gdHJ1ZVxyXG5cdH1cclxuXHRsb2FkU2NlbmUoY2IpIHtcclxuXHRcdExheWEubG9hZGVyLmxvYWQoJ3Jlcy9hdGxhcy9yZW1vdGUvcmFuay5hdGxhcycsIExheWEuSGFuZGxlci5jcmVhdGUodGhpcywgZnVuY3Rpb24gKGRhdGEpIHtcclxuXHRcdFx0TGF5YS5TY2VuZS5vcGVuKCdzY2VuZXMvY29tbW9uL1JhbmsvT0RDUmFua1ZpZXcuc2NlbmUnLCB0cnVlLCBudWxsLCBMYXlhLkhhbmRsZXIuY3JlYXRlKHRoaXMsIGZ1bmN0aW9uIChzY2VuZSkge1xyXG5cdFx0XHRcdGNiKHNjZW5lKVxyXG5cdFx0XHR9KSlcclxuXHRcdH0pKVxyXG5cdH1cclxufVxyXG5cclxuLy/mv4DmtLvlkK/liqjnsbtcclxubGV0IG1haW4gPSBuZXcgTWFpbigpO1xyXG5cclxuaWYgKHdpbmRvdy53eCkge1xyXG5cdHd4Lm9uTWVzc2FnZShmdW5jdGlvbiAoZGF0YSkge1xyXG5cdFx0c3dpdGNoIChkYXRhLnR5cGUpIHtcclxuXHRcdFx0Y2FzZSAnc2hvd1JhbmtWaWV3JzpcclxuXHRcdFx0XHREYXRhQ2VudGVyLnJlcXVlc3RGcmllbmRMaXN0KChsaXN0LCBpbmZvKSA9PiB7XHJcblx0XHRcdFx0XHRtYWluLmxvYWRTY2VuZShmdW5jdGlvbihzY2VuZSl7XHJcblx0XHRcdFx0XHRcdHNjZW5lLnJlY2VpdmVEYXRhKGxpc3QsIGluZm8pXHJcblx0XHRcdFx0XHR9KVxyXG5cdFx0XHRcdH0pXHJcblx0XHRcdFx0YnJlYWtcclxuXHRcdFx0Y2FzZSAnc2hvd1JhbmtHcm91cFZpZXcnOlxyXG5cdFx0XHRcdGxldCBzaGFyZVRpY2tldCA9IGRhdGEuc2hhcmVUaWNrZXRcclxuXHRcdFx0XHREYXRhQ2VudGVyLnJlcXVlc3RHcm91cExpc3Qoc2hhcmVUaWNrZXQsIChsaXN0LCBpbmZvKSA9PiB7XHJcblx0XHRcdFx0XHRtYWluLmxvYWRTY2VuZShmdW5jdGlvbihzY2VuZSl7XHJcblx0XHRcdFx0XHRcdHNjZW5lLnJlY2VpdmVEYXRhKGxpc3QsIGluZm8pXHJcblx0XHRcdFx0XHR9KVxyXG5cdFx0XHRcdH0pXHJcblx0XHRcdFx0YnJlYWtcclxuXHRcdH1cclxuXHR9KVxyXG59XHJcbiIsImV4cG9ydCBkZWZhdWx0IGNsYXNzIFJhbmtDZWxsIGV4dGVuZHMgTGF5YS5Cb3gge1xuICAgIG9uQXdha2UoKXtcbiAgICAgICAgdGhpcy5pbWdJY29uID0gdGhpcy5nZXRDaGlsZEJ5TmFtZSgnaW1nSWNvbicpXG4gICAgICAgIHRoaXMubGJsUmFuayA9IHRoaXMuZ2V0Q2hpbGRCeU5hbWUoJ2xibFJhbmsnKVxuICAgICAgICB0aGlzLmxibE5hbWUgPSB0aGlzLmdldENoaWxkQnlOYW1lKCdsYmxOYW1lJylcbiAgICAgICAgdGhpcy5sYmxDb3VudCA9IHRoaXMuZ2V0Q2hpbGRCeU5hbWUoJ2xibENvdW50JylcbiAgICB9XG4gICAgc2V0SXRlbShpdGVtKXtcbiAgICAgICAgdGhpcy5sYmxSYW5rLnRleHQgPSBpdGVtLnJhbmtcbiAgICAgICAgdGhpcy5pbWdJY29uLnNraW4gPSBpdGVtLmF2YXRhclVybFxuICAgICAgICB0aGlzLmxibE5hbWUudGV4dCA9IGl0ZW0ubmlja25hbWVcbiAgICAgICAgdGhpcy5sYmxDb3VudC50ZXh0ID0gaXRlbS5kZXRhaWxcbiAgICB9XG59IiwiZXhwb3J0IGRlZmF1bHQgY2xhc3MgUmFua1ZpZXcgZXh0ZW5kcyBMYXlhLlZpZXcge1xuICAgIG9uQXdha2UoKXtcbiAgICAgICAgdGhpcy5jb25maWdMaXN0VmlldygpXG4gICAgfVxuICAgIGNvbmZpZ0xpc3RWaWV3KCl7XG4gICAgICAgIGxldCBsaXN0VmlldyA9IHRoaXMubGlzdFZpZXdcbiAgICAgICAgbGlzdFZpZXcudlNjcm9sbEJhclNraW4gPSBcIlwiXG4gICAgICAgIGxpc3RWaWV3LnJlbmRlckhhbmRsZXIgPSAgTGF5YS5IYW5kbGVyLmNyZWF0ZSh0aGlzLGZ1bmN0aW9uKGNlbGwsaW5kZXgpe1xuICAgICAgICAgICAgbGV0IGl0ZW0gPSBsaXN0Vmlldy5hcnJheVtpbmRleF1cbiAgICAgICAgICAgIGNlbGwuc2V0SXRlbShpdGVtKVxuICAgICAgICAgICAgaWYgKGluZGV4ID09IDApIHtcbiAgICAgICAgICAgICAgICBjZWxsLmxibFJhbmsuY29sb3IgPSBcIiNmZjdlMDBcIjtcbiAgICAgICAgICAgICAgICBjZWxsLmxibFJhbmsuYm9sZCA9IHRydWU7XG4gICAgICAgICAgICB9IGVsc2UgaWYgKGluZGV4ID09IDEgfHwgaW5kZXggPT0gMil7XG4gICAgICAgICAgICAgICAgY2VsbC5sYmxSYW5rLmNvbG9yID0gXCIjNDA0MDQwXCI7XG4gICAgICAgICAgICAgICAgY2VsbC5sYmxSYW5rLmJvbGQgPSB0cnVlO1xuICAgICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgICAgICBjZWxsLmxibFJhbmsuY29sb3IgPSBcIiM3YzdjN2NcIjtcbiAgICAgICAgICAgICAgICBjZWxsLmxibFJhbmsuYm9sZCA9IGZhbHNlO1xuICAgICAgICAgICAgfVxuICAgICAgICB9LG51bGwsZmFsc2UpXG4gICAgfVxuICAgIHJlbG9hZERhdGEobGlzdCl7XG4gICAgICAgIHRoaXMubGlzdFZpZXcucmVwZWF0WSA9IGxpc3QubGVuZ3RoID4gNSA/IDU6bGlzdC5sZW5ndGhcbiAgICAgICAgdGhpcy5saXN0Vmlldy5hcnJheSA9IGxpc3RcbiAgICAgICAgdGhpcy5saXN0Vmlldy5yZWZyZXNoKClcbiAgICB9XG4gICAgcmVsb2FkTXlSYW5rVmlld0RhdGEoZGF0YSl7XG4gICAgICAgIHRoaXMubXlSYW5rVmlldy5zZXRJdGVtKGRhdGEpXG4gICAgfVxuICAgIHJlY2VpdmVEYXRhKGxpc3QsaW5mbyl7XG4gICAgICAgIHRoaXMucmVsb2FkRGF0YShsaXN0KVxuICAgICAgICB0aGlzLnJlbG9hZE15UmFua1ZpZXdEYXRhKGluZm8pXG4gICAgfVxufSIsImltcG9ydCBPcGVuRGF0YUN0eCBmcm9tICcuL09wZW5EYXRhQ3R4J1xuaW1wb3J0IFV0aWwgZnJvbSAnLi9VdGlsJ1xuZXhwb3J0IGRlZmF1bHQgY2xhc3MgRGF0YUNlbnRlciB7XG5cbn1cbi8qKuW9k+WJjeeUqOaIt+aVsOaNriAqL1xuRGF0YUNlbnRlci5mcmllbmRzSW5mbyA9IG51bGxcbi8qKuiHquW3seeUqOaIt+S/oeaBryAqL1xuRGF0YUNlbnRlci5teUluZm8gPSBudWxsXG4vKirlvZPliY3nlKjmiLfor6bnu4bkv6Hmga8gKi9cbkRhdGFDZW50ZXIudXNlciA9IG51bGxcbi8qKlxuICogS1ZMaXN0OltcbiAqICAgIHtrZXk6XCJzY29yZVwiLHZhbHVlOlwiMTAwMFwifSxcbiAqICAgIHtrZXk6XCJtYXhTY29yZVwiLHZhbHVlOlwiMTAwMFwifVxuICogICAge2tleTpcImRldGFpbFwiLHZhbHVlOlwi6K+m5oOFXCJ9LFxuICogICAge2tleTpcInVwZGF0ZV90aW1lXCIsdmFsdWU6XCIxMjM0NTY3ODlcIn0sXG4gKiBdXG4gKi9cbkRhdGFDZW50ZXIubWFrZURhdGEgPSBmdW5jdGlvbiAoZGF0YSwgY2IpIHtcbiAgICBsZXQgbGlzdCA9IHRoaXMuaGFuZGxlTGlzdChkYXRhKVxuICAgIHRoaXMucmVxdWVzdFVzZXJEYXRhKChpbmZvKSA9PiB7XG4gICAgICAgIGluZm8ucmFuayA9IHRoaXMuZmluZFVzZXJSYW5rKGluZm8sIGxpc3QpXG4gICAgICAgIGluZm8uZGV0YWlsID0gdGhpcy5maW5kVXNlckRldGFpbChpbmZvKVxuICAgICAgICBjYiAmJiBjYihsaXN0LCBpbmZvKVxuICAgIH0pXG59XG5EYXRhQ2VudGVyLnJlcXVlc3RGcmllbmRMaXN0ID0gZnVuY3Rpb24gKGNiKSB7XG4gICAgT3BlbkRhdGFDdHguZ2V0RnJpZW5kRGF0YSgocmVzKSA9PiB7XG4gICAgICAgIHRoaXMubWFrZURhdGEocmVzLmRhdGEsIGNiKVxuICAgIH0pXG59XG5EYXRhQ2VudGVyLnJlcXVlc3RHcm91cExpc3QgPSBmdW5jdGlvbiAoc2hhcmVUaWNrZXQsIGNiKSB7XG4gICAgT3BlbkRhdGFDdHguZ2V0R3JvdXBEYXRhKHNoYXJlVGlja2V0LCAocmVzKSA9PiB7XG4gICAgICAgIHRoaXMubWFrZURhdGEocmVzLmRhdGEsIGNiKVxuICAgIH0pXG59XG4vKirlkJHmnI3liqHlmajmm7TmlrDjgJDmnIDpq5jliIbjgJEgKi9cbkRhdGFDZW50ZXIudXBkYXRlTWF4U2NvcmUgPSBmdW5jdGlvbiAocGFyYW1zKSB7XG4gICAgaWYgKCFwYXJhbXNbT3BlbkRhdGFDdHguU0NPUkVfS0VZXSkge1xuICAgICAgICBjb25zb2xlLmVycm9yKFwi5b+F6aG75oyH5a6a55So5oi355qE5YiG5pWwXCIpXG4gICAgICAgIHJldHVyblxuICAgIH1cbiAgICBsZXQga3ZMaXN0ID0gW11cblxuICAgIGxldCBjZW50ZXIgPSBEYXRhQ2VudGVyLmNlbnRlclxuICAgIGxldCBteUluZm8gPSBjZW50ZXIubXlJbmZvXG4gICAgaWYgKCFteUluZm8pIHsgcmV0dXJuIH1cbiAgICBsZXQgc2NvcmUgPSBwYXJhbXNbT3BlbkRhdGFDdHguU0NPUkVfS0VZXVxuICAgIGxldCBtYXhTY29yZSA9IG15SW5mb1tPcGVuRGF0YUN0eC5TQ09SRV9NQVhfS0VZXVxuICAgIG1heFNjb3JlID0gTWF0aC5tYXgobWF4U2NvcmUsIHNjb3JlKVxuXG4gICAga3ZMaXN0LnB1c2goe1xuICAgICAgICBrZXk6IE9wZW5EYXRhQ3R4LlNDT1JFX0tFWSxcbiAgICAgICAgdmFsdWU6IG1heFNjb3JlICsgXCJcIlxuICAgIH0pXG4gICAga3ZMaXN0LnB1c2goe1xuICAgICAgICBrZXk6IE9wZW5EYXRhQ3R4LlNDT1JFX01BWF9LRVksXG4gICAgICAgIHZhbHVlOiBtYXhTY29yZSArIFwiXCJcbiAgICB9KVxuXG4gICAgaWYgKHBhcmFtc1tPcGVuRGF0YUN0eC5ERVNfS0VZXSkge1xuICAgICAgICBrdkxpc3QucHVzaCh7XG4gICAgICAgICAgICBrZXk6IE9wZW5EYXRhQ3R4LkRFU19LRVksXG4gICAgICAgICAgICB2YWx1ZTogcGFyYW1zW09wZW5EYXRhQ3R4LkRFU19LRVldXG4gICAgICAgIH0pXG4gICAgfSBlbHNlIHtcbiAgICAgICAga3ZMaXN0LnB1c2goe1xuICAgICAgICAgICAga2V5OiBPcGVuRGF0YUN0eC5ERVNfS0VZLFxuICAgICAgICAgICAgdmFsdWU6IG1heFNjb3JlICsgcGFyYW1zWyd1bml0J11cbiAgICAgICAgfSlcbiAgICB9XG4gICAgT3BlbkRhdGFDdHguc2V0KGt2TGlzdClcbn1cbi8qKuiOt+WPluS4quS6uuS/oeaBryAqL1xuRGF0YUNlbnRlci5yZXF1ZXN0TXlJbmZvID0gZnVuY3Rpb24gKGNiKSB7XG4gICAgaWYgKHRoaXMudXNlcikgeyBjYiAmJiBjYih0aGlzLnVzZXIpIH1cbiAgICBPcGVuRGF0YUN0eC5nZXRNeUluZm8oKHJlcykgPT4ge1xuICAgICAgICBsZXQgdXNlciA9IHJlcy5kYXRhWzBdXG4gICAgICAgIHVzZXIubmlja05hbWUgPSBVdGlsLmZvcm1hdE5hbWUodXNlci5uaWNrTmFtZSlcbiAgICAgICAgdXNlci5hdmF0YXJVcmwgPSBVdGlsLm1ha2VJY29uKHVzZXIuYXZhdGFyVXJsKVxuICAgICAgICB0aGlzLnVzZXIgPSB1c2VyXG4gICAgICAgIGNiICYmIGNiKHRoaXMudXNlcilcbiAgICB9KVxufVxuRGF0YUNlbnRlci5yZXF1ZXN0VXNlckRhdGEgPSBmdW5jdGlvbiAoY2IpIHtcbiAgICB0aGlzLnJlcXVlc3RNeUluZm8oKHVzZXIpID0+IHtcbiAgICAgICAgT3BlbkRhdGFDdHguZ2V0VXNlckRhdGEoKHJlcykgPT4ge1xuICAgICAgICAgICAgbGV0IGluZm8gPSB7XG4gICAgICAgICAgICAgICAgb3BlbmlkOiBcIlwiLFxuICAgICAgICAgICAgICAgIG5pY2tuYW1lOiB1c2VyLm5pY2tOYW1lLFxuICAgICAgICAgICAgICAgIGF2YXRhclVybDogdXNlci5hdmF0YXJVcmwsXG4gICAgICAgICAgICAgICAgS1ZEYXRhTGlzdDogcmVzLktWRGF0YUxpc3RcbiAgICAgICAgICAgIH1cbiAgICAgICAgICAgIGNiICYmIGNiKGluZm8pXG4gICAgICAgIH0pXG4gICAgfSlcbn1cblxuRGF0YUNlbnRlci5oYW5kbGVMaXN0ID0gZnVuY3Rpb24gKGxpc3QpIHtcbiAgICBsZXQgcmVzdWx0ID0gW11cbiAgICBmb3IgKGxldCBpID0gMCwgbGVuZ3RoID0gbGlzdC5sZW5ndGg7IGkgPCBsZW5ndGg7IGkrKykge1xuICAgICAgICBsZXQgaW5mbyA9IGxpc3RbaV1cbiAgICAgICAgbGV0IGt2TGlzdCA9IGluZm8uS1ZEYXRhTGlzdFxuICAgICAgICBpZiAoIWt2TGlzdCB8fCBrdkxpc3QubGVuZ3RoIDw9IDApIHtcbiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoXCLlvZPliY3mlbDmja7kuI3lrZjlnKjmjIflrprnmoRLVkxpc3Q6XFxuXCIpXG4gICAgICAgICAgICBjb25zb2xlLmxvZyhKU09OLnN0cmluZ2lmeShpbmZvKSlcbiAgICAgICAgICAgIGNvbnRpbnVlXG4gICAgICAgIH1cbiAgICAgICAgLy8gVXRpbC5mbGF0KGluZm8sICdLVkRhdGFMaXN0JylcblxuICAgICAgICAvLyBpZiAoIWluZm9bT3BlbkRhdGFDdHguU0NPUkVfS0VZXSkgeyBjb250aW51ZSB9XG4gICAgICAgIC8vIGlmICghaW5mb1tPcGVuRGF0YUN0eC5ERVNfS0VZXSkge1xuICAgICAgICAvLyAgICAgaW5mb1tPcGVuRGF0YUN0eC5ERVNfS0VZXSA9IGluZm9bT3BlbkRhdGFDdHguU0NPUkVfS0VZXVxuICAgICAgICAvLyB9XG5cbiAgICAgICAgaW5mby5uaWNrbmFtZSA9IFV0aWwuZm9ybWF0TmFtZShpbmZvLm5pY2tuYW1lKVxuICAgICAgICBpbmZvLmF2YXRhclVybCA9IFV0aWwubWFrZUljb24oaW5mby5hdmF0YXJVcmwpXG4gICAgICAgIHJlc3VsdC5wdXNoKGluZm8pXG4gICAgfVxuICAgIHJlc3VsdC5mb3JFYWNoKChpdGVtLCBpZHgpID0+IHtcbiAgICAgICAgaXRlbS5yYW5rID0gYE5PLiR7aWR4ICsgMX1gXG4gICAgICAgIGl0ZW0uZGV0YWlsID0gdGhpcy5maW5kVXNlckRldGFpbChpdGVtKVxuICAgIH0pXG4gICAgcmVzdWx0LnNvcnQoKGxocywgcmhzKSA9PiB7XG4gICAgICAgIHJldHVybiByaHMuS1ZEYXRhTGlzdFtPcGVuRGF0YUN0eC5TQ09SRV9JTkRFWF0udmFsdWUgLSBsaHMuS1ZEYXRhTGlzdFtPcGVuRGF0YUN0eC5TQ09SRV9JTkRFWF0udmFsdWVcbiAgICB9KVxuICAgIHJldHVybiByZXN1bHRcbn1cbkRhdGFDZW50ZXIuZmluZFVzZXJSYW5rID0gZnVuY3Rpb24gKHVzZXIsIGxpc3QpIHtcbiAgICBsZXQgdXNlclJhbmsgPSAtMVxuICAgIGZvciAobGV0IGkgPSAwOyBpIDwgbGlzdC5sZW5ndGg7IGkrKykge1xuICAgICAgICBsZXQgaW5mbyA9IGxpc3RbaV1cbiAgICAgICAgaWYgKGluZm8uYXZhdGFyVXJsID09IHVzZXIuYXZhdGFyVXJsIHx8IGluZm8ubmlja25hbWUgPT0gdXNlci5uaWNrbmFtZSkge1xuICAgICAgICAgICAgdXNlclJhbmsgPSBpXG4gICAgICAgIH1cbiAgICAgICAgaW5mby5yYW5rID0gXCJOTy5cIiArIChpICsgMSlcbiAgICB9XG4gICAgcmV0dXJuICh1c2VyUmFuayA9PSAtMSkgPyBcIuacquS4iuamnFwiIDogKFwiTk8uXCIgKyAodXNlclJhbmsgKyAxKSlcbn1cbkRhdGFDZW50ZXIuZmluZFVzZXJEZXRhaWwgPSBmdW5jdGlvbiAoaW5mbykge1xuICAgIGxldCBkZXRhaWwgPSAnJ1xuICAgIGlmIChpbmZvLktWRGF0YUxpc3QubGVuZ3RoID4gT3BlbkRhdGFDdHguREVUQUlMX0lOREVYKSB7XG4gICAgICAgIGRldGFpbCA9IGluZm8uS1ZEYXRhTGlzdFtPcGVuRGF0YUN0eC5ERVRBSUxfSU5ERVhdLnZhbHVlIHx8IGluZm8uS1ZEYXRhTGlzdFtPcGVuRGF0YUN0eC5TQ09SRV9JTkRFWF0udmFsdWUgfHwgJydcbiAgICB9IGVsc2Uge1xuICAgICAgICBkZXRhaWwgPSBpbmZvLktWRGF0YUxpc3RbT3BlbkRhdGFDdHguU0NPUkVfSU5ERVhdLnZhbHVlIHx8ICcnXG4gICAgfVxuICAgIHJldHVybiBkZXRhaWxcbn0iLCJleHBvcnQgZGVmYXVsdCBjbGFzcyBPcGVuRGF0YUN0eCB7XG5cblxufVxuLyoq5o+P6L+w5L+h5oGv77yM55So5LqO55WM6Z2i5bGV56S6ICovXG5PcGVuRGF0YUN0eC5ERVNfS0VZID0gXCJkZXRhaWxcIlxuLyoq55So5oi35pWw5o2u5pu05paw5pe26Ze0ICovXG5PcGVuRGF0YUN0eC5VUERBVEVfVElNRV9LRVkgPSAndXBkYXRlVGltZSdcbi8qKueUqOaIt+W9k+WJjeiOt+WPlueahOWIhuaVsO+8iOi/meS4quW+iOmHjeimge+8jOeUqOS6juaOkuW6j++8iSAqL1xuT3BlbkRhdGFDdHguU0NPUkVfS0VZID0gJ3Njb3JlJ1xuLyoq55So5oi355qE5pyA6auY5YiGICovXG5PcGVuRGF0YUN0eC5TQ09SRV9NQVhfS0VZID0gJ21heFNjb3JlJ1xuT3BlbkRhdGFDdHgua2V5cyA9IFtcbiAgICBPcGVuRGF0YUN0eC5TQ09SRV9LRVksXG4gICAgT3BlbkRhdGFDdHguREVTX0tFWSxcbiAgICBPcGVuRGF0YUN0eC5TQ09SRV9NQVhfS0VZLFxuICAgIE9wZW5EYXRhQ3R4LlVQREFURV9USU1FX0tFWVxuXVxuT3BlbkRhdGFDdHguU0NPUkVfSU5ERVggPSBPcGVuRGF0YUN0eC5rZXlzLmluZGV4T2YoT3BlbkRhdGFDdHguU0NPUkVfS0VZKVxuT3BlbkRhdGFDdHguREVUQUlMX0lOREVYID0gT3BlbkRhdGFDdHgua2V5cy5pbmRleE9mKE9wZW5EYXRhQ3R4LkRFU19LRVkpXG5cbi8qKuiOt+WPluWlveWPi+S/oeaBryAqL1xuT3BlbkRhdGFDdHguZ2V0RnJpZW5kRGF0YSA9IGZ1bmN0aW9uIChjYikge1xuICAgIHd4LmdldEZyaWVuZENsb3VkU3RvcmFnZSh7XG4gICAgICAgIGtleUxpc3Q6IHRoaXMua2V5cyxcbiAgICAgICAgc3VjY2VzczogY2JcbiAgICB9KVxufVxuLyoq6I635Y+W576k55So5oi35L+h5oGvICovXG5PcGVuRGF0YUN0eC5nZXRHcm91cERhdGEgPSBmdW5jdGlvbiAoc2hhcmVUaWNrZXQsIGNiKSB7XG4gICAgd3guZ2V0R3JvdXBDbG91ZFN0b3JhZ2Uoe1xuICAgICAgICBzaGFyZVRpY2tldDogc2hhcmVUaWNrZXQsXG4gICAgICAgIGtleUxpc3Q6IHRoaXMua2V5cyxcbiAgICAgICAgc3VjY2VzczogY2JcbiAgICB9KVxufVxuLyoq6I635Y+W55So5oi35pWw5o2uICovXG5PcGVuRGF0YUN0eC5nZXRVc2VyRGF0YSA9IGZ1bmN0aW9uIChjYikge1xuICAgIHd4LmdldFVzZXJDbG91ZFN0b3JhZ2Uoe1xuICAgICAgICBrZXlMaXN0OiB0aGlzLmtleXMsXG4gICAgICAgIHN1Y2Nlc3M6IGNiXG4gICAgfSlcbn1cbi8qKuiOt+WPlueUqOaIt+S/oeaBryAqL1xuT3BlbkRhdGFDdHguZ2V0VXNlckluZm8gPSBmdW5jdGlvbiAodXNlcnMsIGNiKSB7XG4gICAgd3guZ2V0VXNlckluZm8oe1xuICAgICAgICBvcGVuSWRMaXN0OiB1c2VycyxcbiAgICAgICAgbGFuZzogXCJ6aF9DTlwiLFxuICAgICAgICBzdWNjZXNzOiBjYlxuICAgIH0pXG59XG4vKirojrflj5boh6rlt7HnmoTkv6Hmga8gKi9cbk9wZW5EYXRhQ3R4LmdldE15SW5mbyA9IGZ1bmN0aW9uIChjYikge1xuICAgIHRoaXMuZ2V0VXNlckluZm8oW1wic2VsZk9wZW5JZFwiXSwgY2IpXG59XG5cbi8qKuiuvue9rueUqOaIt+aVsOaNriAqL1xuT3BlbkRhdGFDdHguc2V0ID0gZnVuY3Rpb24gKGt2TGlzdCkge1xuICAgIC8vMeOAgeagvOW8j+WMluaVsOaNrlxuICAgIGt2TGlzdC5mb3JFYWNoKGVsZW1lbnQgPT4ge1xuICAgICAgICBsZXQgdmFsdWUgPSBlbGVtZW50LnZhbHVlXG4gICAgICAgIGlmICh0eXBlb2YgdmFsdWUgIT0gJ3N0cmluZycpIHtcbiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoYOW9k+WJjeS8oOWFpeaVsOaNruagvOW8j+acieivrzpgKVxuICAgICAgICAgICAgY29uc29sZS5lcnJvcihKU09OLnN0cmluZ2lmeShlbGVtZW50KSlcbiAgICAgICAgICAgIGVsZW1lbnQudmFsdWUgPSBTdHJpbmcodmFsdWUpXG4gICAgICAgIH1cbiAgICB9KTtcbiAgICBsZXQgdGltZSA9IERhdGUubm93KClcbiAgICBsZXQgdGltZUludGVydmFsID0gTnVtYmVyKHRpbWUpIC8gMTAwMFxuICAgIGt2TGlzdC5wdXNoKHsga2V5OiB0aGlzLlVQREFURV9USU1FX0tFWSwgdmFsdWU6IHRpbWVJbnRlcnZhbCArIFwiXCIgfSlcbiAgICBjb25zb2xlLmxvZyhgT0QgfCBTRVQgfCAke0pTT04uc3RyaW5naWZ5KGt2TGlzdCl9YClcbiAgICB3eC5zZXRVc2VyQ2xvdWRTdG9yYWdlKHtcbiAgICAgICAgS1ZEYXRhTGlzdDoga3ZMaXN0LFxuICAgICAgICBzdWNjZXNzKHJlcykge1xuICAgICAgICAgICAgY29uc29sZS5sb2coXCJPRCB8IFNFVCB8IFNVQyB8IFwiICsgSlNPTi5zdHJpbmdpZnkocmVzKSk7XG4gICAgICAgIH0sXG4gICAgICAgIGZhaWwocmVzKSB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcIk9EIHwgU0VUIHwgRkFJTCB8IFwiICsgSlNPTi5zdHJpbmdpZnkocmVzKSk7XG4gICAgICAgIH1cbiAgICB9KVxufVxuXG4vKirnp7vpmaTnlKjmiLfmlbDmja4gKi9cbk9wZW5EYXRhQ3R4LnJlbW92ZSA9IGZ1bmN0aW9uIChrZXlzKSB7XG4gICAgd3gucmVtb3ZlVXNlckNsb3VkU3RvcmFnZSh7XG4gICAgICAgIGtleUxpc3Q6IGtleXMsXG4gICAgICAgIHN1Y2Nlc3MocmVzKSB7XG4gICAgICAgICAgICBjb25zb2xlLmxvZyhcIk9EIHwgUkVNT1ZFIHwgU1VDIHwgXCIgKyBKU09OLnN0cmluZ2lmeShyZXMpKTtcbiAgICAgICAgfSxcbiAgICAgICAgZmFpbChyZXMpIHtcbiAgICAgICAgICAgIGNvbnNvbGUubG9nKFwiT0QgfCBSRU1PVkUgfCBGQUlMIHwgXCIgKyBKU09OLnN0cmluZ2lmeShyZXMpKTtcbiAgICAgICAgfVxuICAgIH0pXG59IiwiZXhwb3J0IGRlZmF1bHQgY2xhc3MgVXRpbCB7XG5cbn1cblV0aWwubWFrZUljb24gPSBmdW5jdGlvbiAodXJsKSB7XG4gICAgdmFyIGl0ZW1zID0gdXJsLnNwbGl0KFwiL1wiKSB8fCBbXTtcbiAgICBpZiAoaXRlbXMubGVuZ3RoID4gMSkge1xuICAgICAgICB2YXIgc3RyID0gaXRlbXNbaXRlbXMubGVuZ3RoIC0gMV07XG4gICAgICAgIGl0ZW1zLnBvcCgpXG4gICAgICAgIGl0ZW1zLnB1c2goXCI5NlwiKVxuICAgICAgICByZXR1cm4gaXRlbXMuam9pbignLycpO1xuICAgIH1cbiAgICByZXR1cm4gdGhpcyArIFwiXCI7XG59XG5VdGlsLmZvcm1hdE5hbWUgPSBmdW5jdGlvbiAobmFtZSkge1xuICAgIHZhciBuID0gMTA7XG4gICAgdmFyIHN0ciA9IG5hbWU7XG4gICAgdmFyIHIgPSAvW15cXHgwMC1cXHhmZl0vZztcbiAgICBpZiAoc3RyLnJlcGxhY2UociwgXCJtbVwiKS5sZW5ndGggPD0gbikge1xuICAgICAgICByZXR1cm4gc3RyICsgXCJcIjtcbiAgICB9XG4gICAgdmFyIG0gPSBNYXRoLmZsb29yKG4gLyAyKTtcbiAgICBmb3IgKHZhciBpID0gbTsgaSA8IHN0ci5sZW5ndGg7IGkrKykge1xuICAgICAgICBpZiAoc3RyLnN1YnN0cmluZygwLCBpKS5yZXBsYWNlKHIsIFwibW1cIikubGVuZ3RoID49IG4pIHtcbiAgICAgICAgICAgIHJldHVybiBzdHIuc3Vic3RyaW5nKDAsIGkpICsgXCIuLi5cIjtcbiAgICAgICAgfVxuICAgIH1cbiAgICByZXR1cm4gc3RyO1xufVxuLyoq5bCGb2Jq55qEa2V555qE5YC877yM5LuO5LiA5Liq5pWw57uE77yM5pig5bCE5Li65LiA5Liq5a+56LGhICovXG5VdGlsLmZsYXQgPSBmdW5jdGlvbiAob2JqLCBrZXksIG1hcCkge1xuICAgIGxldCBsaXN0ID0gb2JqW2tleV1cbiAgICBpZiAoIWxpc3QpIHsgcmV0dXJuIH1cbiAgICBsaXN0LmZvckVhY2goZWxlbWVudCA9PiB7XG4gICAgICAgIGxldCBrZXkgPSBlbGVtZW50WydrZXknXVxuICAgICAgICBpZiAoa2V5KSB7XG4gICAgICAgICAgICBpZiAob2JqW2tleV0pIHtcbiAgICAgICAgICAgICAgICBjb25zb2xlLmVycm9yKGAke29ian3lkKvmnInmjIflrprnmoQke2tleX1gKVxuICAgICAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgICAgICBvYmpba2V5XSA9IGVsZW1lbnRbJ3ZhbHVlJ11cbiAgICAgICAgICAgIH1cbiAgICAgICAgfSBlbHNlIHtcbiAgICAgICAgICAgIGNvbnNvbGUuZXJyb3IoYCR7ZWxlbWVudH3kuI3lrZjlnKjmjIflrprnmoRrZXlgKVxuICAgICAgICB9XG4gICAgfSlcbn0iXX0=
