/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameResultView from "./scripts/common/GameResult/GameResultView"
import OtherGameList from "./scripts/prefab/OtherGameList"
import GameResultControl from "./scripts/common/GameResult/GameResultControl"
import GameAgainControl from "./scripts/common/GameResult/GameAgainControl"
import GameListOrBannerControl from "./scripts/common/GameResult/GameListOrBannerControl"
import TurnTableView from "./scripts/common/GameResult/TurnTableView"
import TurnTableControl from "./scripts/common/GameResult/TurnTableControl"
import FBView from "./scripts/common/FriendBattle/FBView"
import NewTask from "./scripts/prefab/NewTask"
import FBControl from "./scripts/common/FriendBattle/FBControl"
import LoadingView from "./scripts/common/Loading/LoadingView"
import LoadingControl from "./scripts/common/Loading/LoadingControl"
import IntegralMallView from "./scripts/common/IntegralMallView"
import BeanBox from "./scripts/prefab/BeanBox"
import UserBox from "./scripts/prefab/UserBox"
import Back from "./scripts/prefab/Back"
import IntegralMallControl from "./scripts/common/IntegralMallControl"
import MatchGradeView from "./scripts/common/MatchGradeService/MatchGradeView"
import BackUpDialogButton from "./scripts/prefab/BackUpDialogButton"
import SkipMall from "./scripts/prefab/SkipMall"
import FBButton from "./scripts/common/FriendBattle/FBButton"
import Marquee from "./scripts/prefab/Marquee"
import MatchGradeControl from "./scripts/common/MatchGradeService/MatchGradeControl"
import MatchView from "./scripts/common/MatchService/MatchView"
import UserView from "./scripts/prefab/UserView"
import MatchControl from "./scripts/common/MatchService/MatchControl"
import QTRoomView from "./scripts/common/QTRoom/QTRoomView"
import QTRoomControl from "./scripts/common/QTRoom/QTRoomControl"
import RankView from "./scripts/common/RankService/RankView"
import RankCell from "./scripts/common/RankService/RankCell"
import RankGroupView from "./scripts/common/RankService/RankGroupView"
import RankGroupControl from "./scripts/common/RankService/RankGroupControl"
import RankControl from "./scripts/common/RankService/RankControl"
import ChargeDialog from "./scripts/dialog/ChargeDialog"
import CrossLinkDialog from "./scripts/dialog/CrossLinkDialog"
import CrossLinkControl from "./scripts/dialog/CrossLinkControl"
import ExchangeMoneyDialog from "./scripts/dialog/ExchangeMoneyDialog"
import CustomerService from "./scripts/prefab/CustomerService"
import MoneyBalance from "./scripts/prefab/MoneyBalance"
import DoubleDialog from "./scripts/dialog/DoubleDialog"
import ExchangeGiftDialog from "./scripts/dialog/ExchangeGiftDialog"
import GameAgainDialog from "./scripts/dialog/GameAgainDialog"
import GameRuleDialog from "./scripts/dialog/GameRuleDialog"
import LoginReward from "./scripts/dialog/LoginReward"
import LoginRewardControl from "./scripts/dialog/LoginRewardControl"
import MoreGameDialog from "./scripts/dialog/MoreGameDialog"
import MiniGameSpine from "./scripts/prefab/MiniGameSpine"
import NotEnoughDialog from "./scripts/dialog/NotEnoughDialog"
import NoVideoDialog from "./scripts/dialog/NoVideoDialog"
import RouletteRewardDialog from "./scripts/common/View/RouletteRewardDialog"
import SettingDialog from "./scripts/dialog/SettingDialog"
import TaskDialog from "./scripts/dialog/TaskDialog"
import TaskReward from "./scripts/dialog/TaskReward"
import MoreGameButton from "./scripts/prefab/MoreGameButton"
import HomeControl from "./scripts/common/HomeControl"
import RouletteView from "./scripts/common/View/RouletteView"
import WxIcon from "./scripts/prefab/WxIcon"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/common/GameResult/GameResultView.js",GameResultView);
		reg("scripts/prefab/OtherGameList.js",OtherGameList);
		reg("scripts/common/GameResult/GameResultControl.js",GameResultControl);
		reg("scripts/common/GameResult/GameAgainControl.js",GameAgainControl);
		reg("scripts/common/GameResult/GameListOrBannerControl.js",GameListOrBannerControl);
		reg("scripts/common/GameResult/TurnTableView.js",TurnTableView);
		reg("scripts/common/GameResult/TurnTableControl.js",TurnTableControl);
		reg("scripts/common/FriendBattle/FBView.js",FBView);
		reg("scripts/prefab/NewTask.js",NewTask);
		reg("scripts/common/FriendBattle/FBControl.js",FBControl);
		reg("scripts/common/Loading/LoadingView.js",LoadingView);
		reg("scripts/common/Loading/LoadingControl.js",LoadingControl);
		reg("scripts/common/IntegralMallView.js",IntegralMallView);
		reg("scripts/prefab/BeanBox.js",BeanBox);
		reg("scripts/prefab/UserBox.js",UserBox);
		reg("scripts/prefab/Back.js",Back);
		reg("scripts/common/IntegralMallControl.js",IntegralMallControl);
		reg("scripts/common/MatchGradeService/MatchGradeView.js",MatchGradeView);
		reg("scripts/prefab/BackUpDialogButton.js",BackUpDialogButton);
		reg("scripts/prefab/SkipMall.js",SkipMall);
		reg("scripts/common/FriendBattle/FBButton.js",FBButton);
		reg("scripts/prefab/Marquee.js",Marquee);
		reg("scripts/common/MatchGradeService/MatchGradeControl.js",MatchGradeControl);
		reg("scripts/common/MatchService/MatchView.js",MatchView);
		reg("scripts/prefab/UserView.js",UserView);
		reg("scripts/common/MatchService/MatchControl.js",MatchControl);
		reg("scripts/common/QTRoom/QTRoomView.js",QTRoomView);
		reg("scripts/common/QTRoom/QTRoomControl.js",QTRoomControl);
		reg("scripts/common/RankService/RankView.js",RankView);
		reg("scripts/common/RankService/RankCell.js",RankCell);
		reg("scripts/common/RankService/RankGroupView.js",RankGroupView);
		reg("scripts/common/RankService/RankGroupControl.js",RankGroupControl);
		reg("scripts/common/RankService/RankControl.js",RankControl);
		reg("scripts/dialog/ChargeDialog.js",ChargeDialog);
		reg("scripts/dialog/CrossLinkDialog.js",CrossLinkDialog);
		reg("scripts/dialog/CrossLinkControl.js",CrossLinkControl);
		reg("scripts/dialog/ExchangeMoneyDialog.js",ExchangeMoneyDialog);
		reg("scripts/prefab/CustomerService.js",CustomerService);
		reg("scripts/prefab/MoneyBalance.js",MoneyBalance);
		reg("scripts/dialog/DoubleDialog.js",DoubleDialog);
		reg("scripts/dialog/ExchangeGiftDialog.js",ExchangeGiftDialog);
		reg("scripts/dialog/GameAgainDialog.js",GameAgainDialog);
		reg("scripts/dialog/GameRuleDialog.js",GameRuleDialog);
		reg("scripts/dialog/LoginReward.js",LoginReward);
		reg("scripts/dialog/LoginRewardControl.js",LoginRewardControl);
		reg("scripts/dialog/MoreGameDialog.js",MoreGameDialog);
		reg("scripts/prefab/MiniGameSpine.js",MiniGameSpine);
		reg("scripts/dialog/NotEnoughDialog.js",NotEnoughDialog);
		reg("scripts/dialog/NoVideoDialog.js",NoVideoDialog);
		reg("scripts/common/View/RouletteRewardDialog.js",RouletteRewardDialog);
		reg("scripts/dialog/SettingDialog.js",SettingDialog);
		reg("scripts/dialog/TaskDialog.js",TaskDialog);
		reg("scripts/dialog/TaskReward.js",TaskReward);
		reg("scripts/prefab/MoreGameButton.js",MoreGameButton);
		reg("scripts/common/HomeControl.js",HomeControl);
		reg("scripts/common/View/RouletteView.js",RouletteView);
		reg("scripts/prefab/WxIcon.js",WxIcon);
    }
}
GameConfig.width = 640;
GameConfig.height = 1136;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "scenes/common/Loading/LoadWaitingView.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
